
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package man.svc.datastatic;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:09:02.797+07:00
 * Generated source version: 2.7.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "DataStaticInvestorService",
                      portName = "DataStaticInvestorServicePort",
                      targetNamespace = "http://www.mandiri.co.id/services/DataStaticInvestor",
                      wsdlLocation = "file:/C:/Eclipse/workspace/ClientMonitoringTool/WebContent/WEB-INF/wsdl/DataStaticInvestor.wsdl",
                      endpointInterface = "man.svc.datastatic.DataStaticInvestorService")
                      
public class DataStaticInvestorServiceImpl implements DataStaticInvestorService {

    private static final Logger LOG = Logger.getLogger(DataStaticInvestorServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see man.svc.datastatic.DataStaticInvestorService#requestDataStaticInvestor(man.svc.datastatic.schema.DataStaticInvestorRequest  part )*
     */
    public man.svc.datastatic.schema.DataStaticInvestorResponse requestDataStaticInvestor(man.svc.datastatic.schema.DataStaticInvestorRequest part) { 
        LOG.info("Executing operation requestDataStaticInvestor");
        System.out.println(part);
        try {
            man.svc.datastatic.schema.DataStaticInvestorResponse _return = new man.svc.datastatic.schema.DataStaticInvestorResponse();
            java.util.List<man.svc.datastatic.schema.ksei.MessageType> _returnMessage = new java.util.ArrayList<man.svc.datastatic.schema.ksei.MessageType>();
            man.svc.datastatic.schema.ksei.MessageType _returnMessageVal1 = new man.svc.datastatic.schema.ksei.MessageType();
            java.util.List<man.svc.datastatic.schema.ksei.MessageType.Field> _returnMessageVal1Field = new java.util.ArrayList<man.svc.datastatic.schema.ksei.MessageType.Field>();
            _returnMessageVal1.getField().addAll(_returnMessageVal1Field);
            java.util.List<man.svc.datastatic.schema.ksei.MessageType.List> _returnMessageVal1List = new java.util.ArrayList<man.svc.datastatic.schema.ksei.MessageType.List>();
            _returnMessageVal1.getList().addAll(_returnMessageVal1List);
            _returnMessageVal1.setName("Name1768205794");
            _returnMessageVal1.setType("Type490231532");
            _returnMessage.add(_returnMessageVal1);
            _return.getMessage().addAll(_returnMessage);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
