package man.svc.datastatic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:09:02.820+07:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.mandiri.co.id/services/DataStaticInvestor", name = "DataStaticInvestorService")
@XmlSeeAlso({man.svc.datastatic.schema.ObjectFactory.class, man.svc.datastatic.schema.ksei.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DataStaticInvestorService {

    @WebResult(name = "DataStaticInvestorResponse", targetNamespace = "http://www.mandiri.co.id/schema/DataStaticInvestor", partName = "part")
    @WebMethod(action = "http://www.mandiri.co.id/services/DataStaticInvestor/requestDataStaticInvestor")
    public man.svc.datastatic.schema.DataStaticInvestorResponse requestDataStaticInvestor(
        @WebParam(partName = "part", name = "DataStaticInvestorRequest", targetNamespace = "http://www.mandiri.co.id/schema/DataStaticInvestor")
        man.svc.datastatic.schema.DataStaticInvestorRequest part
    );
}
