
package man.svc.datastatic;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:09:02.719+07:00
 * Generated source version: 2.7.10
 * 
 */
public final class DataStaticInvestorService_DataStaticInvestorServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.mandiri.co.id/services/DataStaticInvestor", "DataStaticInvestorService");

    private DataStaticInvestorService_DataStaticInvestorServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DataStaticInvestorService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DataStaticInvestorService_Service ss = new DataStaticInvestorService_Service(wsdlURL, SERVICE_NAME);
        DataStaticInvestorService port = ss.getDataStaticInvestorServicePort();  
        
        {
        System.out.println("Invoking requestDataStaticInvestor...");
        man.svc.datastatic.schema.DataStaticInvestorRequest _requestDataStaticInvestor_part = new man.svc.datastatic.schema.DataStaticInvestorRequest();
        _requestDataStaticInvestor_part.setUsername("AR001");
        _requestDataStaticInvestor_part.setPassword("bebas");
        man.svc.datastatic.schema.DataStaticInvestorResponse _requestDataStaticInvestor__return = port.requestDataStaticInvestor(_requestDataStaticInvestor_part);
        System.out.println("requestDataStaticInvestor.result=" + _requestDataStaticInvestor__return);


        }

        System.exit(0);
    }

}
