package man.svc.statement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:12:11.792+07:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.mandiri.co.id/services/InvestorAcctStatement", name = "InvestorAcctStatementService")
@XmlSeeAlso({man.svc.statement.schema.ObjectFactory.class, man.svc.statement.schema.ksei.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InvestorAcctStatementService {

    @WebResult(name = "InvestorAcctStatementResponse", targetNamespace = "http://www.mandiri.co.id/schema/InvestorAcctStatement", partName = "part")
    @WebMethod(action = "http://www.mandiri.co.id/services/InvestorAcctStatement/requestStatement")
    public man.svc.statement.schema.InvestorAcctStatementResponse requestStatement(
        @WebParam(partName = "part", name = "InvestorAcctStatementRequest", targetNamespace = "http://www.mandiri.co.id/schema/InvestorAcctStatement")
        man.svc.statement.schema.InvestorAcctStatementRequest part
    );
}
