
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package man.svc.statement;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:12:11.773+07:00
 * Generated source version: 2.7.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "InvestorAcctStatementService",
                      portName = "InvestorAcctStatementServicePort",
                      targetNamespace = "http://www.mandiri.co.id/services/InvestorAcctStatement",
                      wsdlLocation = "file:/C:/Eclipse/workspace/ClientMonitoringTool/WebContent/WEB-INF/wsdl/Statement.wsdl",
                      endpointInterface = "man.svc.statement.InvestorAcctStatementService")
                      
public class InvestorAcctStatementServiceImpl implements InvestorAcctStatementService {

    private static final Logger LOG = Logger.getLogger(InvestorAcctStatementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see man.svc.statement.InvestorAcctStatementService#requestStatement(man.svc.statement.schema.InvestorAcctStatementRequest  part )*
     */
    public man.svc.statement.schema.InvestorAcctStatementResponse requestStatement(man.svc.statement.schema.InvestorAcctStatementRequest part) { 
        LOG.info("Executing operation requestStatement");
        System.out.println(part);
        try {
            man.svc.statement.schema.InvestorAcctStatementResponse _return = new man.svc.statement.schema.InvestorAcctStatementResponse();
            java.util.List<man.svc.statement.schema.ksei.MessageType> _returnMessage = new java.util.ArrayList<man.svc.statement.schema.ksei.MessageType>();
            man.svc.statement.schema.ksei.MessageType _returnMessageVal1 = new man.svc.statement.schema.ksei.MessageType();
            java.util.List<man.svc.statement.schema.ksei.MessageType.Field> _returnMessageVal1Field = new java.util.ArrayList<man.svc.statement.schema.ksei.MessageType.Field>();
            _returnMessageVal1.getField().addAll(_returnMessageVal1Field);
            java.util.List<man.svc.statement.schema.ksei.MessageType.List> _returnMessageVal1List = new java.util.ArrayList<man.svc.statement.schema.ksei.MessageType.List>();
            _returnMessageVal1.getList().addAll(_returnMessageVal1List);
            _returnMessageVal1.setName("Name-1300089007");
            _returnMessageVal1.setType("Type1911485360");
            _returnMessage.add(_returnMessageVal1);
            _return.getMessage().addAll(_returnMessage);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
