package man.svc.heartbeat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:05:04.505+07:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.mandiri.co.id/services/Heartbeat", name = "HeartbeatService")
@XmlSeeAlso({man.svc.heartbeat.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HeartbeatService {

    @WebResult(name = "HeartbeatResponse", targetNamespace = "http://www.mandiri.co.id/schema/Heartbeat", partName = "part")
    @WebMethod(action = "http://www.mandiri.co.id/services/Heartbeat/sendHeartbeat")
    public man.svc.heartbeat.schema.HeartbeatResponse sendHeartbeat(
        @WebParam(partName = "part", name = "HeartbeatRequest", targetNamespace = "http://www.mandiri.co.id/schema/Heartbeat")
        man.svc.heartbeat.schema.HeartbeatRequest part
    );
}
