
package man.svc.heartbeat;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:05:04.432+07:00
 * Generated source version: 2.7.10
 * 
 */
public final class HeartbeatService_HeartbeatServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.mandiri.co.id/services/Heartbeat", "HeartbeatService");

    private HeartbeatService_HeartbeatServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HeartbeatService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HeartbeatService_Service ss = new HeartbeatService_Service(wsdlURL, SERVICE_NAME);
        HeartbeatService port = ss.getHeartbeatServicePort();  
        
        {
        System.out.println("Invoking sendHeartbeat...");
        man.svc.heartbeat.schema.HeartbeatRequest _sendHeartbeat_part = new man.svc.heartbeat.schema.HeartbeatRequest();
        _sendHeartbeat_part.setUsername("AR001");
        _sendHeartbeat_part.setPassword("bebas");
        man.svc.heartbeat.schema.HeartbeatResponse _sendHeartbeat__return = port.sendHeartbeat(_sendHeartbeat_part);
        System.out.println("sendHeartbeat.result=" + _sendHeartbeat__return.getStatus());


        }

        System.exit(0);
    }

}
