
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package man.svc.heartbeat;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:05:04.487+07:00
 * Generated source version: 2.7.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "HeartbeatService",
                      portName = "HeartbeatServicePort",
                      targetNamespace = "http://www.mandiri.co.id/services/Heartbeat",
                      wsdlLocation = "file:/C:/Eclipse/workspace/ClientMonitoringTool/WebContent/WEB-INF/wsdl/Heartbeat.wsdl",
                      endpointInterface = "man.svc.heartbeat.HeartbeatService")
                      
public class HeartbeatServiceImpl implements HeartbeatService {

    private static final Logger LOG = Logger.getLogger(HeartbeatServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see man.svc.heartbeat.HeartbeatService#sendHeartbeat(man.svc.heartbeat.schema.HeartbeatRequest  part )*
     */
    public man.svc.heartbeat.schema.HeartbeatResponse sendHeartbeat(man.svc.heartbeat.schema.HeartbeatRequest part) { 
        LOG.info("Executing operation sendHeartbeat");
        System.out.println(part);
        try {
            man.svc.heartbeat.schema.HeartbeatResponse _return = new man.svc.heartbeat.schema.HeartbeatResponse();
            _return.setStatus("Status695423702");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
