
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package man.svc.validation;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-25T08:44:26.952+07:00
 * Generated source version: 2.7.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "BrokerValidationService",
                      portName = "BrokerValidationServicePort",
                      targetNamespace = "http://www.mandiri.co.id/services/BrokerValidation",
                      wsdlLocation = "file:/C:/Eclipse/workspace/ClientMonitoringTool/WebContent/WEB-INF/wsdl/Validation.wsdl",
                      endpointInterface = "man.svc.validation.BrokerValidationService")
                      
public class BrokerValidationServiceImpl implements BrokerValidationService {

    private static final Logger LOG = Logger.getLogger(BrokerValidationServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see man.svc.validation.BrokerValidationService#requestBrokerValidation(man.svc.validation.schema.BrokerValidationRequest  part )*
     */
    public man.svc.validation.schema.BrokerValidationResponse requestBrokerValidation(man.svc.validation.schema.BrokerValidationRequest part) { 
        LOG.info("Executing operation requestBrokerValidation");
        System.out.println(part);
        try {
            man.svc.validation.schema.BrokerValidationResponse _return = new man.svc.validation.schema.BrokerValidationResponse();
            java.util.List<man.svc.validation.schema.ValidationType> _returnValidation = new java.util.ArrayList<man.svc.validation.schema.ValidationType>();
            man.svc.validation.schema.ValidationType _returnValidationVal1 = new man.svc.validation.schema.ValidationType();
            _returnValidationVal1.setWsUser("WsUser611648779");
            _returnValidationVal1.setWsPasswd("WsPasswd2015427520");
            _returnValidation.add(_returnValidationVal1);
            _return.getValidation().addAll(_returnValidation);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
