
package man.svc.validation;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-25T08:44:26.890+07:00
 * Generated source version: 2.7.10
 * 
 */
public final class BrokerValidationService_BrokerValidationServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.mandiri.co.id/services/BrokerValidation", "BrokerValidationService");

    private BrokerValidationService_BrokerValidationServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BrokerValidationService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BrokerValidationService_Service ss = new BrokerValidationService_Service(wsdlURL, SERVICE_NAME);
        BrokerValidationService port = ss.getBrokerValidationServicePort();  
        
        {
        System.out.println("Invoking requestBrokerValidation...");
        man.svc.validation.schema.BrokerValidationRequest _requestBrokerValidation_part = new man.svc.validation.schema.BrokerValidationRequest();
        _requestBrokerValidation_part.setUsername("Username1168136221");
        _requestBrokerValidation_part.setSerialNumber("SerialNumber-1811420629");
        man.svc.validation.schema.BrokerValidationResponse _requestBrokerValidation__return = port.requestBrokerValidation(_requestBrokerValidation_part);
        System.out.println("requestBrokerValidation.result=" + _requestBrokerValidation__return);


        }

        System.exit(0);
    }

}
