package man.svc.validation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-25T08:44:26.976+07:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.mandiri.co.id/services/BrokerValidation", name = "BrokerValidationService")
@XmlSeeAlso({man.svc.validation.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BrokerValidationService {

    @WebResult(name = "BrokerValidationResponse", targetNamespace = "http://www.mandiri.co.id/schema/BrokerValidation", partName = "part")
    @WebMethod(action = "http://www.mandiri.co.id/services/BrokerValidation/requestBrokerValidation")
    public man.svc.validation.schema.BrokerValidationResponse requestBrokerValidation(
        @WebParam(partName = "part", name = "BrokerValidationRequest", targetNamespace = "http://www.mandiri.co.id/schema/BrokerValidation")
        man.svc.validation.schema.BrokerValidationRequest part
    );
}
