package man.svc.balance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:10:43.763+07:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.mandiri.co.id/services/InvestorAcctBalance", name = "InvestorAcctBalanceService")
@XmlSeeAlso({man.svc.balance.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InvestorAcctBalanceService {

    @WebResult(name = "InvestorAcctBalanceResponse", targetNamespace = "http://www.mandiri.co.id/schema/InvestorAcctBalance", partName = "part")
    @WebMethod(action = "http://www.mandiri.co.id/services/InvestorAcctBalance/requestBalance")
    public man.svc.balance.schema.InvestorAcctBalanceResponse requestBalance(
        @WebParam(partName = "part", name = "InvestorAcctBalanceRequest", targetNamespace = "http://www.mandiri.co.id/schema/InvestorAcctBalance")
        man.svc.balance.schema.InvestorAcctBalanceRequest part
    );
}
