
package man.svc.balance;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2016-05-16T22:10:43.694+07:00
 * Generated source version: 2.7.10
 * 
 */
public final class InvestorAcctBalanceService_InvestorAcctBalanceServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.mandiri.co.id/services/InvestorAcctBalance", "InvestorAcctBalanceService");

    private InvestorAcctBalanceService_InvestorAcctBalanceServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InvestorAcctBalanceService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InvestorAcctBalanceService_Service ss = new InvestorAcctBalanceService_Service(wsdlURL, SERVICE_NAME);
        InvestorAcctBalanceService port = ss.getInvestorAcctBalanceServicePort();  
        
        {
        System.out.println("Invoking requestBalance...");
        man.svc.balance.schema.InvestorAcctBalanceRequest _requestBalance_part = new man.svc.balance.schema.InvestorAcctBalanceRequest();
        _requestBalance_part.setUsername("AR001");
        _requestBalance_part.setPassword("bebas");
        man.svc.balance.schema.InvestorAcctBalanceResponse _requestBalance__return = port.requestBalance(_requestBalance_part);
        System.out.println("requestBalance.result=" + _requestBalance__return);


        }

        System.exit(0);
    }

}
